'use client';
import {
  AtSign, Bitcoin, Building2, FileText, Fingerprint, Globe, Hash, Image as ImageIcon, Link2, MapPin, Network, Phone, Server, ShieldCheck, User, UserSquare2, KeyRound, Tag,
} from 'lucide-react';
import { Badge, type BadgeTone } from '@/components/ui/badge';
import { Tooltip } from '@/components/ui/tooltip';
import { CATEGORY_LABELS, CLAIM_TYPE_LABELS, CONFIDENCE_LABELS, GEO_PRECISION_LABELS, VERIFICATION_LABELS, ENTITY_LABELS, type ClaimType, type ConfidenceLevel, type EntityType, type EvidenceCategory, type GeoPrecision, type VerificationStatus } from '@/shared/domain';
import { cn } from '@/lib/cn';

const CONF_TONE: Record<ConfidenceLevel, BadgeTone> = { verified: 'success', high: 'accent', moderate: 'warning', low: 'danger', unverified: 'neutral' };
const CONF_BARS: Record<ConfidenceLevel, number> = { verified: 4, high: 3, moderate: 2, low: 1, unverified: 0 };

export function ConfidenceBadge({ level, rationale, score }: { level: string; rationale?: string[]; score?: number }) {
  const l = (level in CONF_TONE ? level : 'unverified') as ConfidenceLevel;
  const badge = (
    <Badge tone={CONF_TONE[l]} className="gap-1.5" data-testid="confidence-badge">
      <span aria-hidden className="flex items-end gap-px">
        {[1, 2, 3, 4].map((i) => (
          <span key={i} className={cn('w-[3px] rounded-[1px]', i <= CONF_BARS[l] ? 'bg-current' : 'bg-current/25')} style={{ height: 3 + i * 2 }} />
        ))}
      </span>
      {CONFIDENCE_LABELS[l]}
    </Badge>
  );
  if (!rationale?.length) return badge;
  return (
    <Tooltip
      content={
        <div className="space-y-1">
          <p className="font-semibold">Why {CONFIDENCE_LABELS[l].toLowerCase()}?</p>
          <ul className="list-disc space-y-0.5 pl-4">
            {rationale.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
          {score !== undefined ? <p className="text-muted">Rule points: {score} (ordinal, not a probability)</p> : null}
        </div>
      }
    >
      <button type="button" className="rounded-md">
        {badge}
      </button>
    </Tooltip>
  );
}

const CLAIM_TONE: Record<ClaimType, BadgeTone> = { FACT: 'info', SOURCE_CLAIM: 'violet', INFERENCE: 'warning', UNVERIFIED_LEAD: 'neutral' };

export function ClaimTypeBadge({ type }: { type: string }) {
  const t = (type in CLAIM_TONE ? type : 'UNVERIFIED_LEAD') as ClaimType;
  return (
    <Tooltip content={CLAIM_TYPE_LABELS[t].description}>
      <span>
        <Badge tone={CLAIM_TONE[t]} className={cn('uppercase tracking-wide', t === 'UNVERIFIED_LEAD' && 'border-dashed')}>
          {CLAIM_TYPE_LABELS[t].label}
        </Badge>
      </span>
    </Tooltip>
  );
}

const VER_TONE: Record<VerificationStatus, BadgeTone> = { unreviewed: 'neutral', verified: 'success', disputed: 'warning', false_positive: 'danger' };

export function VerificationBadge({ status }: { status: string }) {
  const s = (status in VER_TONE ? status : 'unreviewed') as VerificationStatus;
  return <Badge tone={VER_TONE[s]}>{VERIFICATION_LABELS[s]}</Badge>;
}

const STATUS_TONE: Record<string, BadgeTone> = {
  draft: 'neutral',
  queued: 'info',
  running: 'accent',
  partially_completed: 'warning',
  completed: 'success',
  failed: 'danger',
  cancelled: 'neutral',
  succeeded: 'success',
  skipped: 'neutral',
  processing: 'accent',
  processed: 'success',
};

export function StatusBadge({ status, className }: { status: string; className?: string }) {
  const label = status === 'partially_completed' ? 'Partially completed' : status.charAt(0).toUpperCase() + status.slice(1).replace(/_/g, ' ');
  return (
    <Badge tone={STATUS_TONE[status] ?? 'neutral'} className={className} data-testid="status-badge" data-status={status}>
      {status === 'running' || status === 'processing' ? <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-current" aria-hidden /> : null}
      {label}
    </Badge>
  );
}

export function SimulatedBadge({ className }: { className?: string }) {
  return (
    <Tooltip content="Generated by a simulated demo provider with fictional data. Not intelligence.">
      <span>
        <Badge tone="simulated" className={cn('font-semibold uppercase tracking-wide', className)} data-testid="simulated-badge">
          Simulated
        </Badge>
      </span>
    </Tooltip>
  );
}

export function ModeBadge({ mode }: { mode: string }) {
  return mode === 'demo' ? <SimulatedBadge /> : <Badge tone="accent">Live</Badge>;
}

export function CategoryBadge({ category }: { category: string }) {
  return <Badge tone="neutral">{CATEGORY_LABELS[category as EvidenceCategory] ?? category}</Badge>;
}

export function GeoPrecisionBadge({ precision }: { precision: string }) {
  const tone: BadgeTone = precision === 'exact' ? 'danger' : precision === 'approximate' ? 'warning' : precision === 'city' ? 'accent' : 'neutral';
  return <Badge tone={tone}>{GEO_PRECISION_LABELS[precision as GeoPrecision] ?? precision}</Badge>;
}

const ENTITY_ICONS: Record<string, typeof User> = {
  person: User,
  username: AtSign,
  email: AtSign,
  domain: Globe,
  ip: Server,
  organization: Building2,
  location: MapPin,
  image: ImageIcon,
  document: FileText,
  social_account: UserSquare2,
  crypto_address: Bitcoin,
  phone: Phone,
  url: Link2,
  asn: Network,
  certificate: ShieldCheck,
  keyword: Hash,
};

export function EntityIcon({ type, className }: { type: string; className?: string }) {
  const Icon = ENTITY_ICONS[type] ?? Tag;
  return <Icon className={cn('h-4 w-4 shrink-0', className)} aria-hidden />;
}

export function EntityTypeLabel({ type }: { type: string }) {
  return (
    <span className="inline-flex items-center gap-1.5 text-xs text-muted">
      <EntityIcon type={type} className="h-3.5 w-3.5" />
      {ENTITY_LABELS[type as EntityType] ?? type}
    </span>
  );
}

export const ProviderKindIcon = { live: Fingerprint, local: KeyRound };

export const ENTITY_COLORS: Record<string, string> = {
  person: '#e879f9',
  username: '#a78bfa',
  email: '#60a5fa',
  domain: '#34d399',
  ip: '#fbbf24',
  organization: '#f472b6',
  location: '#f87171',
  image: '#2dd4bf',
  document: '#94a3b8',
  social_account: '#818cf8',
  crypto_address: '#facc15',
  phone: '#fb923c',
  url: '#22d3ee',
  asn: '#eab308',
  certificate: '#4ade80',
  keyword: '#cbd5e1',
};
