import type { ColumnType, Generated, Insertable, Selectable, Updateable } from 'kysely';

/**
 * Database schema shared by the SQLite and PostgreSQL dialects.
 * - IDs are UUID strings generated by the application.
 * - Timestamps are ISO-8601 strings (TEXT in SQLite, TIMESTAMPTZ in PostgreSQL, normalised on read).
 * - JSON columns are TEXT in SQLite and JSONB in PostgreSQL; use `toJson`/`fromJson` helpers.
 * - Booleans are stored as integers 0/1 in both dialects.
 */
type Json = ColumnType<unknown, string, string>;
type Ts = string;
type Bool = number;

export interface UsersTable {
  id: string;
  email: string;
  name: string;
  password_hash: string;
  role: 'analyst' | 'admin';
  preferences: Json;
  created_at: Ts;
  updated_at: Ts;
  last_login_at: Ts | null;
}

export interface SessionsTable {
  id: string;
  user_id: string;
  token_hash: string;
  created_at: Ts;
  expires_at: Ts;
  last_seen_at: Ts;
  user_agent: string | null;
  ip_hash: string | null;
}

export interface InvestigationsTable {
  id: string;
  owner_id: string;
  name: string;
  description: string | null;
  scope_statement: string | null;
  depth: 'quick' | 'standard' | 'deep' | 'custom';
  mode: 'live' | 'demo';
  modules: Json;
  providers: Json;
  status: string;
  created_at: Ts;
  updated_at: Ts;
  started_at: Ts | null;
  completed_at: Ts | null;
  retention_until: Ts | null;
}

export interface TargetsTable {
  id: string;
  investigation_id: string;
  type: string;
  raw_value: string;
  normalized_value: string;
  label: string | null;
  metadata: Json;
  created_at: Ts;
}

export interface InvestigationJobsTable {
  id: string;
  investigation_id: string;
  kind: string;
  status: string;
  attempt: number;
  locked_by: string | null;
  locked_at: Ts | null;
  heartbeat_at: Ts | null;
  cancel_requested: Bool;
  total_tasks: number;
  completed_tasks: number;
  failed_tasks: number;
  skipped_tasks: number;
  stage: string | null;
  error: string | null;
  payload: Json;
  created_at: Ts;
  started_at: Ts | null;
  finished_at: Ts | null;
}

export interface JobTasksTable {
  id: string;
  job_id: string;
  investigation_id: string;
  provider_id: string;
  target_id: string | null;
  entity_id: string | null;
  operation: string;
  stage: string;
  input: Json;
  status: string;
  attempts: number;
  started_at: Ts | null;
  finished_at: Ts | null;
  duration_ms: number | null;
  result_count: number;
  error_category: string | null;
  error_message: string | null;
  notes: Json;
  created_at: Ts;
}

export interface SourcesTable {
  id: string;
  investigation_id: string;
  provider_id: string;
  source_key: string;
  name: string;
  url: string | null;
  reliability: string;
  kind: 'live' | 'local' | 'simulated';
  first_seen_at: Ts;
}

export interface ObservationsTable {
  id: string;
  investigation_id: string;
  task_id: string | null;
  provider_id: string;
  source_id: string;
  target_id: string | null;
  entity_type: string;
  normalized_value: string;
  title: string;
  description: string | null;
  excerpt: string | null;
  source_url: string | null;
  published_at: Ts | null;
  published_precision: string | null;
  collected_at: Ts;
  category: string;
  claim_type: string;
  metadata: Json;
  confidence_inputs: Json;
  limitations: Json;
  is_simulated: Bool;
  fingerprint: string;
}

export interface EvidenceTable {
  id: string;
  investigation_id: string;
  observation_id: string | null;
  artifact_id: string | null;
  kind: string;
  title: string;
  content: string;
  content_type: string;
  sha256: string;
  source_url: string | null;
  provider_id: string | null;
  collected_at: Ts;
  is_simulated: Bool;
  redacted: Bool;
}

export interface FindingsTable {
  id: string;
  investigation_id: string;
  entity_id: string | null;
  fingerprint: string;
  title: string;
  description: string | null;
  category: string;
  claim_type: string;
  confidence: string;
  confidence_score: number;
  confidence_rationale: Json;
  verification_status: string;
  source_count: number;
  provider_count: number;
  primary_source_url: string | null;
  primary_provider_id: string;
  collected_at: Ts;
  published_at: Ts | null;
  published_precision: string | null;
  geo_lat: number | null;
  geo_lon: number | null;
  geo_precision: string | null;
  geo_place: string | null;
  geo_country: string | null;
  geo_basis: string | null;
  bookmarked: Bool;
  is_simulated: Bool;
  created_at: Ts;
  updated_at: Ts;
}

export interface FindingObservationsTable {
  finding_id: string;
  observation_id: string;
}

export interface FindingEvidenceTable {
  finding_id: string;
  evidence_id: string;
}

export interface FindingReviewsTable {
  id: string;
  finding_id: string;
  investigation_id: string;
  user_id: string;
  from_status: string;
  to_status: string;
  rationale: string | null;
  created_at: Ts;
}

export interface EntitiesTable {
  id: string;
  investigation_id: string;
  type: string;
  value: string;
  display_value: string;
  attributes: Json;
  cluster_id: string | null;
  is_target: Bool;
  is_simulated: Bool;
  first_seen_at: Ts;
  last_seen_at: Ts;
}

export interface RelationshipsTable {
  id: string;
  investigation_id: string;
  from_entity_id: string;
  to_entity_id: string;
  type: string;
  status: 'confirmed' | 'possible' | 'rejected';
  confidence: string;
  rationale: string | null;
  is_simulated: Bool;
  first_seen_at: Ts;
  last_seen_at: Ts;
}

export interface RelationshipEvidenceTable {
  relationship_id: string;
  evidence_id: string;
}

export interface EntityMatchCandidatesTable {
  id: string;
  investigation_id: string;
  entity_a_id: string;
  entity_b_id: string;
  signals: Json;
  strength: 'strong' | 'moderate' | 'weak';
  status: 'pending' | 'accepted' | 'rejected' | 'separated';
  decided_by: string | null;
  decided_at: Ts | null;
  created_at: Ts;
}

export interface TimelineEventsTable {
  id: string;
  investigation_id: string;
  entity_id: string | null;
  finding_id: string | null;
  event_date: string | null;
  date_precision: string;
  date_kind: string;
  label: string;
  description: string | null;
  source_url: string | null;
  provider_id: string | null;
  is_simulated: Bool;
  fingerprint: string;
  created_at: Ts;
}

export interface ProviderConfigurationsTable {
  id: string;
  user_id: string;
  provider_id: string;
  enabled: Bool;
  settings: Json;
  updated_at: Ts;
}

export interface ProviderHealthTable {
  provider_id: string;
  status: string;
  message: string | null;
  latency_ms: number | null;
  checked_at: Ts;
}

export interface AnalystNotesTable {
  id: string;
  investigation_id: string;
  author_id: string;
  finding_id: string | null;
  entity_id: string | null;
  body: string;
  created_at: Ts;
  updated_at: Ts;
}

export interface TagsTable {
  id: string;
  investigation_id: string;
  name: string;
  color: string;
  created_at: Ts;
}

export interface FindingTagsTable {
  finding_id: string;
  tag_id: string;
}

export interface ReportsTable {
  id: string;
  investigation_id: string;
  created_by: string;
  title: string;
  snapshot: Json;
  options: Json;
  created_at: Ts;
}

export interface ArtifactsTable {
  id: string;
  investigation_id: string;
  uploaded_by: string;
  kind: 'image' | 'document';
  original_name: string;
  stored_path: string;
  mime_type: string;
  size_bytes: number;
  sha256: string;
  phash: string | null;
  width: number | null;
  height: number | null;
  status: string;
  analysis: Json;
  error: string | null;
  created_at: Ts;
}

export interface AiAnalysesTable {
  id: string;
  investigation_id: string;
  created_by: string;
  model: string;
  result: Json;
  created_at: Ts;
}

export interface AuditEventsTable {
  id: string;
  user_id: string | null;
  investigation_id: string | null;
  action: string;
  target_type: string | null;
  target_id: string | null;
  metadata: Json;
  ip_hash: string | null;
  created_at: Ts;
}

export interface Database {
  users: UsersTable;
  sessions: SessionsTable;
  investigations: InvestigationsTable;
  targets: TargetsTable;
  investigation_jobs: InvestigationJobsTable;
  job_tasks: JobTasksTable;
  sources: SourcesTable;
  observations: ObservationsTable;
  evidence: EvidenceTable;
  findings: FindingsTable;
  finding_observations: FindingObservationsTable;
  finding_evidence: FindingEvidenceTable;
  finding_reviews: FindingReviewsTable;
  entities: EntitiesTable;
  relationships: RelationshipsTable;
  relationship_evidence: RelationshipEvidenceTable;
  entity_match_candidates: EntityMatchCandidatesTable;
  timeline_events: TimelineEventsTable;
  provider_configurations: ProviderConfigurationsTable;
  provider_health: ProviderHealthTable;
  analyst_notes: AnalystNotesTable;
  tags: TagsTable;
  finding_tags: FindingTagsTable;
  reports: ReportsTable;
  artifacts: ArtifactsTable;
  ai_analyses: AiAnalysesTable;
  audit_events: AuditEventsTable;
}

export type Row<T extends keyof Database> = Selectable<Database[T]>;
export type NewRow<T extends keyof Database> = Insertable<Database[T]>;
export type RowUpdate<T extends keyof Database> = Updateable<Database[T]>;
export type { Generated };
