import 'server-only';
import PDFDocument from 'pdfkit';
import Papa from 'papaparse';
import type { ReportFinding, ReportSnapshot } from './snapshot';
import { CATEGORY_LABELS, CLAIM_TYPE_LABELS, CONFIDENCE_LABELS, GEO_PRECISION_LABELS, VERIFICATION_LABELS, type ConfidenceLevel, type ClaimType, type EvidenceCategory, type GeoPrecision, type VerificationStatus } from '@/shared/domain';

export type ReportFormat = 'markdown' | 'json' | 'csv' | 'pdf';

const conf = (c: string) => CONFIDENCE_LABELS[c as ConfidenceLevel] ?? c;
const claim = (c: string) => CLAIM_TYPE_LABELS[c as ClaimType]?.label ?? c;
const cat = (c: string) => CATEGORY_LABELS[c as EvidenceCategory] ?? c;
const ver = (v: string) => VERIFICATION_LABELS[v as VerificationStatus] ?? v;
const day = (iso: string | null | undefined) => (iso ? iso.slice(0, 10) : '—');
const dateWithPrecision = (iso: string | null, precision: string | null) => {
  if (!iso) return 'Date unknown';
  if (precision === 'year') return `${iso.slice(0, 4)} (year only)`;
  if (precision === 'month') return `${iso.slice(0, 7)} (month only)`;
  if (precision === 'approximate') return `${iso.slice(0, 16).replace('T', ' ')} (approximate)`;
  if (precision === 'exact') return iso.slice(0, 16).replace('T', ' ') + ' UTC';
  return iso.slice(0, 10);
};

/** Escape characters that would change Markdown structure; content is untrusted. */
function md(text: string | null | undefined): string {
  if (!text) return '';
  return text.replace(/\r?\n+/g, ' ').replace(/([\\`*_{}[\]<>|#])/g, '\\$1');
}

function findingMd(f: ReportFinding): string {
  const lines = [
    `- **[${f.ref}] ${md(f.title)}**${f.isSimulated ? ' _(SIMULATED)_' : ''}`,
    `  - ${claim(f.claimType)} · ${conf(f.confidence)} · ${ver(f.verification)} · ${cat(f.category)}`,
  ];
  if (f.description) lines.push(`  - ${md(f.description)}`);
  if (f.geo) lines.push(`  - Location: ${md(f.geo.place ?? `${f.geo.lat}, ${f.geo.lon}`)} — ${GEO_PRECISION_LABELS[f.geo.precision as GeoPrecision] ?? f.geo.precision}. Basis: ${md(f.geo.basis)}`);
  lines.push(`  - Sources: ${f.providers.map(md).join(', ') || '—'}${f.sourceUrls.length ? ` — ${f.sourceUrls.slice(0, 3).map((u) => `<${u.replace(/[<>]/g, '')}>`).join(', ')}` : ''}`);
  lines.push(`  - Collected ${day(f.collectedAt)}; source date ${dateWithPrecision(f.publishedAt, f.publishedPrecision)}; evidence ${f.evidenceIds.length} item(s)`);
  return lines.join('\n');
}

export function renderMarkdown(s: ReportSnapshot): string {
  const out: string[] = [];
  const section = (n: number, title: string) => out.push('', `## ${n}. ${title}`, '');
  const list = (items: ReportFinding[], empty: string) => {
    if (!items.length) out.push(`_${empty}_`);
    else out.push(...items.map(findingMd));
  };
  out.push(`# ${md(s.title)}`, '');
  if (s.containsSimulatedData) out.push('> **SIMULATED DEMO DATA** — generated by ATLAS demo providers using fictional entities. Not intelligence.', '');
  out.push(`ATLAS OSINT report · generated ${s.generatedAt.replace('T', ' ').slice(0, 19)} UTC by ${md(s.generatedBy)} · report schema v${s.schemaVersion}${s.options.redact ? ' · sensitive values redacted' : ''}`);

  section(1, 'Executive Summary');
  out.push(...s.executiveSummary.map((p) => `${md(p)}\n`));
  if (s.aiSummary) {
    out.push('', '### AI-assisted summary (optional, evidence-cited)', '', `_Generated by ${md(s.aiSummary.model)} at ${s.aiSummary.generatedAt}. Every statement cites findings; ${s.aiSummary.rejectedStatements} uncited statement(s) were discarded._`, '');
    out.push(...s.aiSummary.summary.map((x) => `- ${md(x.text)} [${x.findingRefs.join(', ')}]`));
    if (s.aiSummary.hypotheses.length) out.push('', '**Hypotheses (not established facts):**', ...s.aiSummary.hypotheses.map((x) => `- HYPOTHESIS: ${md(x.text)} [${x.findingRefs.join(', ')}]`));
  }

  section(2, 'Scope and Methodology');
  out.push(`- Investigation: ${md(s.investigation.name)} (${s.investigation.mode === 'demo' ? 'demo mode — simulated providers' : 'live mode'})`);
  if (s.investigation.scope) out.push(`- Scope statement: ${md(s.investigation.scope)}`);
  out.push(`- Depth: ${s.methodology.depth}; started ${day(s.investigation.startedAt)}; completed ${day(s.investigation.completedAt)}; status ${s.investigation.status}`);
  out.push(`- Confidence method: ${md(s.methodology.confidenceMethod)}`, '', '| Provider | Type | Succeeded | Failed | Unavailable | Results |', '| --- | --- | ---: | ---: | ---: | ---: |');
  out.push(...s.methodology.providers.map((p) => `| ${md(p.name)} | ${p.kind} | ${p.succeeded} | ${p.failed} | ${p.skipped} | ${p.results} |`));

  section(3, 'Target Identifiers');
  out.push(...s.targets.map((t) => `- ${t.type}: \`${t.value.replace(/`/g, '')}\`${t.label ? ` (${md(t.label)})` : ''}`));

  section(4, 'Key Findings');
  list(s.keyFindings, 'No findings reached moderate confidence or higher.');
  section(5, 'Public Online Presence');
  list(s.sections.onlinePresence, 'No public online presence findings.');
  section(6, 'Infrastructure');
  list(s.sections.infrastructure, 'No infrastructure findings.');
  section(7, 'Geographic Findings');
  list(s.sections.geographic, 'No geographic findings.');
  section(8, 'Image Intelligence');
  list(s.sections.imageIntelligence, 'No image analysis findings.');
  section(9, 'Document Findings');
  list(s.sections.documents, 'No document findings.');
  if (s.sections.other.length) {
    out.push('', '### Other findings (breach exposure, dark-web leads, phone, cryptocurrency)', '');
    list(s.sections.other, '');
  }

  section(10, 'Entity Relationships');
  if (!s.relationships.length) out.push('_No relationships recorded._');
  else {
    out.push('| From | Relationship | To | Status | Confidence |', '| --- | --- | --- | --- | --- |');
    out.push(...s.relationships.slice(0, 300).map((r) => `| ${md(r.from)} (${r.fromType}) | ${r.type} | ${md(r.to)} (${r.toType}) | ${r.status} | ${conf(r.confidence)} |`));
    if (s.relationships.length > 300) out.push(`| … ${s.relationships.length - 300} more | | | | |`);
  }
  if (s.entityMatches.length) {
    out.push('', '**Entity-resolution candidates** (never merged automatically):', ...s.entityMatches.map((m) => `- ${md(m.a)} ↔ ${md(m.b)} — ${m.strength}, ${m.status}: ${m.signals.map(md).join(' ')}`));
  }

  section(11, 'Timeline');
  if (!s.timeline.length) out.push('_No dated events. ATLAS never invents dates._');
  else {
    out.push('| Date | Event | Entity | Confidence | Finding |', '| --- | --- | --- | --- | --- |');
    out.push(...s.timeline.slice(0, 300).map((t) => `| ${dateWithPrecision(t.date, t.precision)} | ${md(t.label)} | ${md(t.entity)} | ${t.confidence ? conf(t.confidence) : '—'} | ${t.findingRef ?? '—'} |`));
  }

  section(12, 'Contradictions');
  if (!s.contradictions.length) out.push('_No conflicting attribute values were detected between sources._');
  else out.push(...s.contradictions.map((c, i) => `- ${md(c.entityValue)} — **${md(c.attribute)}**: ${c.values.map((v, j) => `"${md(v.value)}" (${(s.contradictions[i]!.providerNames[j] ?? []).map(md).join(', ')})`).join(' vs ')}`));

  section(13, 'Confidence and Verification');
  out.push(`- ${Object.entries(s.stats.byConfidence).map(([k, v]) => `${conf(k)}: ${v}`).join(' · ') || 'No findings'}`);
  out.push(`- Claim types: ${Object.entries(s.stats.byClaimType).map(([k, v]) => `${claim(k)}: ${v}`).join(' · ') || '—'}`);
  out.push(`- Analyst reviews: ${s.verification.length}`);
  out.push(...s.verification.map((v) => `  - ${v.findingRef}: ${ver(v.from)} → ${ver(v.to)} by ${md(v.reviewer)} on ${day(v.at)}${v.rationale ? ` — ${md(v.rationale)}` : ''}`));

  section(14, 'Unverified Leads');
  list(s.unverifiedLeads.slice(0, 100), 'No unverified leads.');
  if (s.unverifiedLeads.length > 100) out.push(`_…and ${s.unverifiedLeads.length - 100} more (see CSV export)._`);

  section(15, 'Limitations');
  out.push(...s.limitations.map((l) => `- ${md(l)}`));

  section(16, 'Source References');
  out.push('| Ref | Provider | Source | URL | Collected | Source date | Findings |', '| --- | --- | --- | --- | --- | --- | --- |');
  out.push(...s.sources.slice(0, 500).map((r) => `| ${r.ref} | ${md(r.provider)} | ${md(r.sourceName)} | ${r.url ? `<${r.url.replace(/[<>|]/g, '')}>` : '—'} | ${day(r.collectedAt)} | ${day(r.publishedAt)} | ${r.findingRefs.slice(0, 8).join(', ')}${r.findingRefs.length > 8 ? '…' : ''} |`));
  out.push('', '---', `Reproducible from stored evidence. Investigation ${s.investigation.id}.`);
  return out.join('\n') + '\n';
}

export function renderCsv(s: ReportSnapshot): string {
  const all = [...new Map([...s.keyFindings, ...Object.values(s.sections).flat(), ...s.unverifiedLeads].map((f) => [f.id, f])).values()].sort((a, b) => a.ref.localeCompare(b.ref));
  // Prefix cells that spreadsheet apps would treat as formulas (CSV injection defence).
  const safe = (v: unknown) => {
    const str = v == null ? '' : String(v);
    return /^[=+\-@\t\r]/.test(str) ? `'${str}` : str;
  };
  return Papa.unparse(
    all.map((f) => ({
      ref: f.ref,
      finding_id: f.id,
      title: safe(f.title),
      description: safe(f.description),
      category: f.category,
      claim_type: f.claimType,
      confidence: f.confidence,
      verification: f.verification,
      entity_type: f.entity?.type ?? '',
      entity: safe(f.entity?.display ?? ''),
      providers: safe(f.providers.join('; ')),
      source_urls: safe(f.sourceUrls.join(' ')),
      collected_at: f.collectedAt,
      source_published_at: f.publishedAt ?? '',
      source_date_precision: f.publishedPrecision ?? '',
      geo_place: safe(f.geo?.place ?? ''),
      geo_lat: f.geo?.lat ?? '',
      geo_lon: f.geo?.lon ?? '',
      geo_precision: f.geo?.precision ?? '',
      evidence_ids: f.evidenceIds.join(' '),
      evidence_sha256: f.evidenceHashes.join(' '),
      simulated: f.isSimulated ? 'yes' : 'no',
      tags: safe(f.tags.join('; ')),
    })),
  );
}

export function renderJson(s: ReportSnapshot): string {
  return JSON.stringify(s, null, 2);
}

// ------------------------------------------------------------------------------------------------ PDF

const COLORS = { ink: '#0f172a', muted: '#475569', accent: '#1d4ed8', rule: '#cbd5e1', warn: '#b45309', simulated: '#b91c1c' };

export async function renderPdf(s: ReportSnapshot): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margins: { top: 56, bottom: 56, left: 56, right: 56 }, info: { Title: s.title, Author: 'ATLAS OSINT', Subject: 'Intelligence report', Creator: 'ATLAS OSINT' }, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
  const width = doc.page.width - 112;
  const clean = (t: string | null | undefined) => (t ?? '').replace(/[^\x09\x0a\x0d\x20-\x7e -ſ–—‘’“”•…→↔]/g, '?');

  const h1 = (t: string) => doc.font('Helvetica-Bold').fontSize(20).fillColor(COLORS.ink).text(clean(t), { width });
  const h2 = (t: string) => {
    if (doc.y > doc.page.height - 140) doc.addPage();
    doc.moveDown(0.8).font('Helvetica-Bold').fontSize(13).fillColor(COLORS.accent).text(clean(t), { width });
    doc.moveTo(56, doc.y + 2).lineTo(56 + width, doc.y + 2).strokeColor(COLORS.rule).lineWidth(0.5).stroke();
    doc.moveDown(0.5);
  };
  const p = (t: string, opts: { color?: string; size?: number; bold?: boolean } = {}) =>
    doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(opts.size ?? 9.5).fillColor(opts.color ?? COLORS.ink).text(clean(t), { width, lineGap: 1.5 });
  const finding = (f: ReportFinding) => {
    if (doc.y > doc.page.height - 110) doc.addPage();
    p(`[${f.ref}] ${f.title}${f.isSimulated ? '  (SIMULATED)' : ''}`, { bold: true, size: 9.5 });
    p(`${claim(f.claimType)} · ${conf(f.confidence)} · ${ver(f.verification)} · ${cat(f.category)}`, { color: COLORS.muted, size: 8.5 });
    if (f.description) p(f.description, { size: 8.5 });
    if (f.geo) p(`Location: ${f.geo.place ?? `${f.geo.lat}, ${f.geo.lon}`} — ${GEO_PRECISION_LABELS[f.geo.precision as GeoPrecision] ?? f.geo.precision}. ${f.geo.basis ?? ''}`, { size: 8.5, color: COLORS.warn });
    p(`Sources: ${f.providers.join(', ')}${f.sourceUrls[0] ? ` — ${f.sourceUrls[0]}` : ''} · collected ${day(f.collectedAt)} · source date ${dateWithPrecision(f.publishedAt, f.publishedPrecision)}`, { size: 7.5, color: COLORS.muted });
    doc.moveDown(0.4);
  };
  const findings = (items: ReportFinding[], empty: string, max = 60) => {
    if (!items.length) return p(empty, { color: COLORS.muted });
    items.slice(0, max).forEach(finding);
    if (items.length > max) p(`…and ${items.length - max} more (see CSV/JSON export).`, { color: COLORS.muted });
  };

  // Cover
  doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.accent).text('ATLAS OSINT', { characterSpacing: 2 });
  doc.moveDown(0.4);
  h1(s.title);
  doc.moveDown(0.3);
  p(`Generated ${s.generatedAt.replace('T', ' ').slice(0, 19)} UTC by ${s.generatedBy} · Investigation ${s.investigation.id}${s.options.redact ? ' · sensitive values redacted' : ''}`, { color: COLORS.muted, size: 8.5 });
  if (s.containsSimulatedData) {
    doc.moveDown(0.6);
    p('SIMULATED DEMO DATA — generated with fictional entities by ATLAS demo providers. Not intelligence.', { bold: true, color: COLORS.simulated, size: 10 });
  }

  h2('1. Executive Summary');
  s.executiveSummary.forEach((x) => { p(x); doc.moveDown(0.3); });
  if (s.aiSummary) {
    p(`AI-assisted summary (${s.aiSummary.model}); every statement cites findings. ${s.aiSummary.rejectedStatements} uncited statement(s) discarded.`, { bold: true, size: 9 });
    s.aiSummary.summary.forEach((x) => p(`• ${x.text} [${x.findingRefs.join(', ')}]`, { size: 9 }));
    s.aiSummary.hypotheses.forEach((x) => p(`• HYPOTHESIS: ${x.text} [${x.findingRefs.join(', ')}]`, { size: 9, color: COLORS.warn }));
  }

  h2('2. Scope and Methodology');
  p(`Mode: ${s.investigation.mode === 'demo' ? 'demo (simulated providers)' : 'live'} · Depth: ${s.methodology.depth} · Status: ${s.investigation.status}`);
  if (s.investigation.scope) p(`Scope: ${s.investigation.scope}`);
  p(`Confidence method: ${s.methodology.confidenceMethod}`, { size: 8.5, color: COLORS.muted });
  doc.moveDown(0.3);
  s.methodology.providers.forEach((pr) => p(`• ${pr.name} (${pr.kind}): ${pr.succeeded} succeeded, ${pr.failed} failed, ${pr.skipped} unavailable, ${pr.results} results${pr.errors[0] && pr.succeeded === 0 ? ` — ${pr.errors[0]}` : ''}`, { size: 8.5 }));

  h2('3. Target Identifiers');
  s.targets.forEach((t) => p(`• ${t.type}: ${t.value}${t.label ? ` (${t.label})` : ''}`));
  h2('4. Key Findings');
  findings(s.keyFindings, 'No findings reached moderate confidence or higher.');
  h2('5. Public Online Presence');
  findings(s.sections.onlinePresence, 'No public online presence findings.');
  h2('6. Infrastructure');
  findings(s.sections.infrastructure, 'No infrastructure findings.');
  h2('7. Geographic Findings');
  findings(s.sections.geographic, 'No geographic findings.');
  h2('8. Image Intelligence');
  findings(s.sections.imageIntelligence, 'No image analysis findings.');
  h2('9. Document Findings');
  findings(s.sections.documents, 'No document findings.');
  if (s.sections.other.length) {
    p('Other findings (breach exposure, dark-web leads, phone, cryptocurrency)', { bold: true });
    findings(s.sections.other, '', 40);
  }
  h2('10. Entity Relationships');
  if (!s.relationships.length) p('No relationships recorded.', { color: COLORS.muted });
  s.relationships.slice(0, 150).forEach((r) => p(`• ${r.from} —${r.type}→ ${r.to} (${r.status}, ${conf(r.confidence)})`, { size: 8.5 }));
  if (s.entityMatches.length) {
    doc.moveDown(0.3);
    p('Entity-resolution candidates (never merged automatically):', { bold: true, size: 9 });
    s.entityMatches.forEach((m) => p(`• ${m.a} ↔ ${m.b}: ${m.strength}, ${m.status}`, { size: 8.5 }));
  }
  h2('11. Timeline');
  if (!s.timeline.length) p('No dated events. ATLAS never invents dates.', { color: COLORS.muted });
  s.timeline.slice(0, 150).forEach((t) => p(`• ${dateWithPrecision(t.date, t.precision)} — ${t.label}${t.findingRef ? ` [${t.findingRef}]` : ''}`, { size: 8.5 }));
  h2('12. Contradictions');
  if (!s.contradictions.length) p('No conflicting attribute values were detected between sources.', { color: COLORS.muted });
  s.contradictions.forEach((c) => p(`• ${c.entityValue} — ${c.attribute}: ${c.values.map((v, j) => `"${v.value}" (${(c.providerNames[j] ?? []).join(', ')})`).join(' vs ')}`, { size: 8.5 }));
  h2('13. Confidence and Verification');
  p(Object.entries(s.stats.byConfidence).map(([k, v]) => `${conf(k)}: ${v}`).join(' · ') || 'No findings');
  p(`Analyst reviews: ${s.verification.length}; verified ${s.stats.verified}; disputed ${s.stats.disputed}; false positives ${s.stats.falsePositives}.`);
  s.verification.forEach((v) => p(`• ${v.findingRef}: ${ver(v.from)} → ${ver(v.to)} by ${v.reviewer} (${day(v.at)})${v.rationale ? ` — ${v.rationale}` : ''}`, { size: 8.5 }));
  h2('14. Unverified Leads');
  findings(s.unverifiedLeads, 'No unverified leads.', 40);
  h2('15. Limitations');
  s.limitations.forEach((l) => p(`• ${l}`, { size: 8.5 }));
  h2('16. Source References');
  s.sources.slice(0, 250).forEach((r) => p(`${r.ref}  ${r.provider} — ${r.sourceName}${r.url ? ` — ${r.url}` : ''} · collected ${day(r.collectedAt)}${r.publishedAt ? ` · source date ${day(r.publishedAt)}` : ''} · ${r.findingRefs.slice(0, 6).join(', ')}`, { size: 7.5 }));

  // Footer on every page.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const footer = `ATLAS OSINT · ${clean(s.investigation.name)}${s.containsSimulatedData ? ' · SIMULATED DATA' : ''} · page ${i + 1} of ${range.count}`;
    doc.font('Helvetica').fontSize(7).fillColor(COLORS.muted).text(footer, 56, doc.page.height - 40, { width, align: 'center', lineBreak: false });
  }
  doc.end();
  return done;
}

export async function renderReport(s: ReportSnapshot, format: ReportFormat): Promise<{ body: Buffer | string; contentType: string; extension: string }> {
  switch (format) {
    case 'markdown':
      return { body: renderMarkdown(s), contentType: 'text/markdown; charset=utf-8', extension: 'md' };
    case 'json':
      return { body: renderJson(s), contentType: 'application/json; charset=utf-8', extension: 'json' };
    case 'csv':
      return { body: renderCsv(s), contentType: 'text/csv; charset=utf-8', extension: 'csv' };
    case 'pdf':
      return { body: await renderPdf(s), contentType: 'application/pdf', extension: 'pdf' };
  }
}
